added custom font-set
...because the error told me to

hugo
Start building sites…
hugo v0.89.4-AB01BA6E+extended linux/amd64 BuildDate=2021-11-17T08:24:09Z VendorInfo=gohugoio
ERROR 2021/12/03 16:52:00 There is a new version of Google Fonts. Learn how to upgrade your font pack at https://wowchemy.com/docs/customization/#custom-font
Error: Error building site: logged 1 error(s)